services:

  db:
    image: postgres
    restart: always
    ports:
      - 5437:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080